apiVersion: v1
kind: Service
metadata:
  labels:
    role: kafka
  name: kafka
spec:
  ports:
  - port: 9092
    targetPort: kafka-port
    protocol: TCP
    name: kafka-port
  selector:
    role: kafka
    name: kafka
  type: LoadBalancer
